
export namespace Errors {

  export type GET_MESSAGE_FROM_DATA_ERROR = "GET_MESSAGE_FROM_DATA_ERROR"
  export type DID_NOT_RESOLVE_MESSAGE = "DID_NOT_RESOLVE_MESSAGE"
  export type RESOLVE_RESPONSE_ERROR = "RESOLVE_RESPONSE_ERROR"
  export type RESOLVE_POTENTIAL_ACTIONS_ERROR = "RESOLVE_POTENTIAL_ACTIONS_ERROR"
  export type RESOLVE_MESSAGE_ERROR = "RESOLVE_MESSAGE_ERROR"
  export type RESOLVE_ROOM_ERROR = "RESOLVE_ROOM_ERROR"

}